library:
  source-dirs: src
tests:
  hasketh-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hasketh
copyright: 2019 Dowland Aiello
maintainer: mitsukomegumii@gmail.com
dependencies:
  - text
  - base16-bytestring
  - base >= 4.7 && < 5
  - blake2
  - bytestring
name: hasketh
version: 0.1.0.0
extra-source-files:
  - README.md
  - ChangeLog.md
author: Dowland Aiello
github: dowlandaiello/hasketh
license: BSD3
executables:
  hasketh-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hasketh
description: Please see the README on GitHub at <https://github.com/githubuser/hasketh#readme>
